package PageObjects;
import org.openqa.selenium.By;
import java.util.HashMap;
import java.util.Map;
public class pageObject31 {
public static Map<String,By > PO= new HashMap<String,By>();
public static Map<String,String > POString= new HashMap<String,String>();
static{
POString.put("产品筛选_确定","xpath;;//div[@aria-label='选择产品']//span[contains(text(),'确定')]");
POString.put("保存为公共用例按钮","xpath;;//span[contains(text(),'保存为公共用例')]");
POString.put("保存成功提示","xpath;;//p[contains(text(),'保存成功')]");
POString.put("引用测试案例","xpath;;//span[contains(text(),'引用测试案例')]");
POString.put("引用测试案例_搜索","cssSelector;;div.el-form-item__content  button[data-v-dcb0bd26].el-button--primary");
POString.put("引用测试案例_用例名称","xpath;;//input[@placeholder='用例名称']");
POString.put("引用测试案例_确定","xpath;;//div[@aria-label='引用测试案例']//span[contains(text(),'确定')]");
POString.put("引用测试案例_选中用例","cssSelector;;div.bt tbody td.el-table-column--selection span.el-checkbox__inner");
POString.put("撤销发布按钮","xpath;;//span[contains(text(),'撤销发布')]");
POString.put("新增用例","xpath;;//div[@class='mb']//span[contains(text(),'新增用例')]");
POString.put("新增用例_优先级","xpath;;//div[@aria-label='测试用例清单']//tbody//td[6]//input");
POString.put("新增个人用例_优先级第一条","xpath;;//li//span[text()='P1']/..");
POString.put("新增用例_前置条件","xpath;;//div[@aria-label='测试用例清单']//tbody//td[3]//textarea");
POString.put("新增用例_功能描述","xpath;;//div[@aria-label='测试用例清单']//tbody//td[2]//textarea");
POString.put("新增用例_归属产品_确定","xpath;;//div[@aria-label='归属产品']//span[contains(text(),'确定')]");
POString.put("新增用例_步骤描述","xpath;;//div[@aria-label='测试用例清单']//tbody//td[4]//textarea");
POString.put("新增用例_预期结果","xpath;;//div[@aria-label='测试用例清单']//tbody//td[5]//textarea");
POString.put("新建用例","xpath;;//span[contains(text(),'新建用例')]");
POString.put("生命阶段确定按钮","xpath;;//div[@x-placement='bottom-start']//span[contains(text(),'确定')]");
POString.put("用例库_个人用例","xpath;;//div[@id='tab-person']");
POString.put("用例库_产品输入框","cssSelector;;.common-left .el-form-item input");
POString.put("用例库_全部模块","xpath;;//span[@title='全部']");
POString.put("用例库_公共用例","xpath;;//div[@id='tab-common']");
POString.put("用例库_分组1","xpath;;//span[@title='分组1']");
POString.put("用例库_分组1菜单","xpath;;//span[@title='分组1']/../..");
POString.put("用例库_分组2","xpath;;//span[@title='分组2']");
POString.put("用例库_分组箭头","xpath;;//span[@class='el-tree-node__expand-icon el-icon-caret-right']");
POString.put("用例库_列表_移动","xpath;;//div[@class='el-table__body-wrapper is-scrolling-right']//tbody//tr[1]//span[text()='移动']");
POString.put("用例库_复制","xpath;;//div[@class='el-table__fixed-right']//span[contains(text(),'复制')]");
POString.put("用例库_归属产品弹窗第一条","cssSelector;;div[class='el-table el-table--fit el-table--striped el-table--fluid-height el-table--enable-row-hover el-table--enable-row-transition'] tbody tr:nth-child(1) td:nth-child(1)");
POString.put("用例库_我创建的","xpath;;//span[contains(text(),'我创建的')]");
POString.put("用例库_新增分组","xpath;;//ul[@x-placement]//li[contains(text(),'新增分组')]");
POString.put("用例库_新增分组输入框","cssSelector;;.el-tree-node__children input");
POString.put("用例库_新增同级分组","xpath;;//ul[@x-placement]//li[contains(text(),'新增同级分组')]");
POString.put("用例库_新增模块","xpath;;//span[@title='新增模块']");
POString.put("用例库_新增模块下分组","xpath;;//span[@title='新增模块']/../../../div[@role='group']");
POString.put("用例库_新建_归属产品_产品名称输入框","cssSelector;;.el-dialog__wrapper .el-row input[placeholder='请输入产品名称']");
POString.put("用例库_新建同级分组菜单","xpath;;//div[@class='el-tree-node__children'][1]//i[@class='el-icon-chat-dot-round el-icon operation']");
POString.put("用例库_用例名称列","xpath;;//tbody//tr[1]//a[contains(@ui-title,'自动化新增用例')]");
POString.put("用例库_移动_目标分组","xpath;;//div[@class='el-dialog__body']//form[@class='el-form']//label[@for='folderId']/following-sibling::div//input");
POString.put("用例库_移动_目标模块","xpath;;//div[@class='el-dialog__body']//form[@class='el-form']//label[@for='moduleId']/following-sibling::div//input");
POString.put("用例库_移动_确定按钮","xpath;;//div[@aria-label='移动']//*[text()='确定']");
POString.put("用例库_解散所有分组","xpath;;//ul[@x-placement]//li[contains(text(),'解散所有分组')]");
POString.put("用例库_解散该分组","xpath;;//ul[@x-placement]//li[contains(text(),'解散该分组')]");
POString.put("用例库_重金属分组菜单键","xpath;;//span[@title='重金属模块']//..//div//i");
POString.put("用例库_重金属模块菜单","xpath;;//span[@title='重金属模块']/../..");
POString.put("用例库列表_创建人","cssSelector;;thead.has-gutter th:nth-child(8) input");
POString.put("用例库列表_生命阶段","xpath;;//div[@class='el-table__fixed-header-wrapper']//span[@title='生命阶段']/../../span[@class='table-list__filter']");
POString.put("新增公共用例_优先级第一条","xpath;;//div[@x-placement='bottom-start']//li[1]");
}
}
