package PageObjects;
import org.openqa.selenium.By;
import java.util.HashMap;
import java.util.Map;
public class pageObject25 {
public static Map<String,By > PO= new HashMap<String,By>();
public static Map<String,String > POString= new HashMap<String,String>();
static{
POString.put("下一步按钮1","cssSelector;;button[gppm-ui=createFlow__next]");
POString.put("下一步按钮2","cssSelector;;button[gppm-ui=createFlow__button__C]");
POString.put("业务模式类别","cssSelector;;#create_FLD_S_00006 i.el-input__icon");
POString.put("业务重要性","cssSelector;;#create_FLD_S_00007 i.el-select__caret");
POString.put("产品大类","cssSelector;;#create_FLD_S_00049 i");
POString.put("先行企划代表","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(5) input.user-picker__input");
POString.put("创新平台负责人","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(4) input.user-picker__input");
POString.put("刷新按钮","cssSelector;;button[gppm-ui=flowList__refresh]");
POString.put("原型机","cssSelector;;#create_FLD_S_00104 i");
POString.put("品质测试代表","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(6) input.user-picker__input");
POString.put("基础平台","cssSelector;;#create_FLD_S_00111 i");
POString.put("工业设计代表","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(14) input.user-picker__input");
POString.put("平台交付评审","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(6) input");
POString.put("平台产品经理","cssSelector;;[for='viewData.1.owners.1.ownerUsers'] +div  input.user-picker__input");
POString.put("平台开发类","cssSelector;;span[title='平台开发类(空调)']");
POString.put("平台技术方案初评","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(2) input");
POString.put("平台确认评审","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(3) input");
POString.put("平台综合方案评审时间","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(5) input");
POString.put("平台项目启动会","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(1) input");
POString.put("必填项校验","cssSelector;;[placeholder='必填项不能为空！']");
POString.put("技术研究负责人","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(2) input.user-picker__input");
POString.put("描述","cssSelector;;#create_REMARK textarea");
POString.put("提示确认按钮","cssSelector;;div.el-message-box button.el-button--primary");
POString.put("新建按钮","cssSelector;;button[gppm-ui=flowList__create]");
POString.put("方案简述","cssSelector;;#create_FLD_A_00041 textarea");
POString.put("普通产品","cssSelector;;span[title=普通产品]");
POString.put("测试建议","cssSelector;;#create_FLD_A_00047 .flow-tinymce-editor");
POString.put("研发主任","cssSelector;;[for='viewData.2.owners.0.ownerUsers'] +div  input.user-picker__input");
POString.put("硬件开发工程师","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(2) input.user-picker__input");
POString.put("结构开发工程师","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(5) input.user-picker__input");
POString.put("结项时间","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(7) input");
POString.put("计划模板","cssSelector;;#create_FLD_S_00090 i");
POString.put("软件开发工程师","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(7) input.user-picker__input");
POString.put("里程碑M1","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(1) input");
POString.put("里程碑M2","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(2) input");
POString.put("里程碑M3","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(4) input");
POString.put("里程碑M4","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(6) input");
POString.put("销售方向","cssSelector;;#create_FLD_S_00048 i");
POString.put("降成本类","cssSelector;;span[title='降成本类']");
POString.put("项目名称","cssSelector;;#create_NAME input[type=text]");
POString.put("项目成员","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(4) input.user-picker__input");
POString.put("项目等级","cssSelector;;#create_FLD_S_00010 i");
POString.put("项目管理","cssSelector;;#create_FLD_U_00066 i");
POString.put("项目管理工程师","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(3) input.user-picker__input");
POString.put("项目类型","cssSelector;;#_projectTypeId i.el-input__icon");
POString.put("项目经理","cssSelector;;#create_MANAGERID i");
POString.put("项目经理成员","cssSelector;;div[id$=ProjectTeamLabel]  div.is-scrolling-none  tr:nth-child(1) input.user-picker__input");
POString.put("预期目标","cssSelector;;#create_FLD_A_00040 textarea");
POString.put("里程碑M5","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(8) input");
POString.put("里程碑M8","cssSelector;;div.Plugin_MilestoneLabel tbody tr:nth-child(13) input");
}
}
