package PageObjects;
import org.openqa.selenium.By;
import java.util.HashMap;
import java.util.Map;
public class pageObject29 {
public static Map<String,By > PO= new HashMap<String,By>();
public static Map<String,String > POString= new HashMap<String,String>();
static{
POString.put("新建缺陷_产品经理","xpath;;//label[text()='产品经理']/following-sibling::div//input[@class='user-picker__input']");
POString.put("新建缺陷_保存草稿","xpath;;//span[contains(text(),'保存草稿')]");
POString.put("新建缺陷_否需要评价","xpath;;//label[contains(text(),'是否需要评价')]/following-sibling::div//label[2]");
POString.put("新建缺陷_失败信息","xpath;;//div[@role='alert']");
POString.put("新建缺陷_审核分配人","xpath;;//div[@title='审核分配']/following-sibling::div//label[text()='审核分配人']/following-sibling::div//div[@class='user-picker__tags']//input");
POString.put("新建缺陷_归属产品选择","xpath;;//tbody//tr[1]//td[1]");
POString.put("新建缺陷_归属产品选择确定","xpath;;//div[@aria-label='归属产品']//div[@class='el-dialog__footer']//span[contains(text(),'确定')]");
POString.put("新建缺陷_提交","xpath;;//span[contains(text(),'提交')]");
POString.put("新建缺陷_解决人","xpath;;//label[text()='解决人']/following-sibling::div//div[@class='user-picker__tags']//input");
POString.put("新建缺陷_评价工程师","xpath;;//label[text()='评价工程师']/following-sibling::div//div[@class='user-picker__tags']//input");
POString.put("新建缺陷_项目经理","xpath;;//div[@title='项目经理确认']/following-sibling::div//input[@class='user-picker__input']");
POString.put("缺陷管理_列表页面","xpath;;//label[contains(text(),'项目筛选')]");
POString.put("缺陷管理_新建","xpath;;//span[contains(text(),'新建')]");
POString.put("缺陷管理_新建页面","xpath;;//div[@class='create-bug-botton']");
POString.put("缺陷管理_标题","xpath;;//tbody//tr[1]//td[not(contains(@class,'is-hidden'))]//a[contains(text(),'自动化测试')]");
POString.put("缺陷管理_流程状态","xpath;;//div[@class='el-table__body-wrapper is-scrolling-left']//tbody//tr[1]");
POString.put("缺陷管理_流程状态2","xpath;;//div[@class='el-table__body-wrapper is-scrolling-left']//table");
POString.put("验证缺陷_作废","xpath;;//div[@class='title-info']//span[contains(text(),'作废')]");
POString.put("验证缺陷_作废提交","xpath;;//div[@aria-label='作废']//span[contains(text(),'提交')]");
POString.put("验证缺陷_处理方案iframe","xpath;;//*[text()='处理方案']/..//*[@class='tox-edit-area__iframe']");
POString.put("验证缺陷_备注文本域","cssSelector;;.el-dialog__wrapper:not([style='display: none;']) textarea");
POString.put("验证缺陷_指派","xpath;;//span[contains(text(),'指派')]");
POString.put("验证缺陷_指派确定","xpath;;//div[@aria-label='指派']//span[contains(text(),'确定')]");
POString.put("验证缺陷_提交验证","xpath;;//span[contains(text(),'提交验证')]");
POString.put("验证缺陷_提交验证确定","xpath;;//div[@aria-label='提交验证']//span[contains(text(),'确定')]");
POString.put("验证缺陷_搁置","xpath;;//span[contains(text(),'搁置')]");
POString.put("验证缺陷_搁置确定","xpath;;//div[@aria-label='搁置']//span[contains(text(),'确定')]");
POString.put("验证缺陷_文本域","cssSelector;;#tinymce");
POString.put("验证缺陷_根本原因","xpath;;//body[@id='tinymce']");
POString.put("验证缺陷_根本原因iframe","xpath;;//*[text()='根本原因']/..//*[@class='tox-edit-area__iframe']");
POString.put("验证缺陷_确认搁置","xpath;;//span[contains(text(),'确认搁置')]");
POString.put("验证缺陷_确认搁置确定","xpath;;//div[@aria-label='确认搁置']//span[contains(text(),'确定')]");
POString.put("验证缺陷_解决人","xpath;;//label[@for='viewData.0.owners.0.ownerUsers']/following-sibling::div//input[not(contains(@readonly,'readonly'))]");
POString.put("验证缺陷_评价","xpath;;//div[@class='gppm-margin flowTabs__button btn-group']//span[contains(text(),'评价')]");
POString.put("验证缺陷_评价确定","xpath;;//div[@aria-label='评价']//span[contains(text(),'确定')]");
POString.put("验证缺陷_输入驳回意见","xpath;;//*[@id='tinymce']");
POString.put("验证缺陷_通过","xpath;;//span[contains(text(),'通过')]");
POString.put("验证缺陷_通过确定","xpath;;//div[@aria-label='通过']//span[contains(text(),'确定')]");
POString.put("验证缺陷_重新打开","xpath;;//span[contains(text(),'重新打开')]");
POString.put("验证缺陷_重新打开确定","xpath;;//div[@aria-label='重新打开']//span[contains(text(),'确定')]");
POString.put("验证缺陷_预计解决版本","xpath;;//*[@for='viewData.1.value']/parent::div[not(contains(@style,'display: none'))]//input[@readonly='readonly']");
POString.put("验证缺陷_驳回","xpath;;//span[contains(text(),'驳回')]");
POString.put("验证缺陷_驳回意见iframe","xpath;;//iframe");
POString.put("验证缺陷_驳回确定","xpath;;//div[@aria-label='驳回']//span[contains(text(),'确定')]");
POString.put("验证缺陷_验证通过","xpath;;//span[contains(text(),'验证通过')]");
POString.put("验证缺陷_验证通过确定","xpath;;//div[@aria-label='验证通过']//span[contains(text(),'确定')]");
POString.put("验证缺陷_撤回","xpath;;//span[contains(text(),'撤回')]");
POString.put("验证缺陷_撤回确定","xpath;;//div[@aria-label='撤回']//span[contains(text(),'确定')]");
POString.put("驳回意见输入框","xpath;;//textarea");
POString.put("搁置_重新打开时间","cssSelector;;.el-dialog__body label[for='viewData.1.value']+div input");
}
}
